- users/kimurayoshimi/3.js
- Find e, and then return index of e as number
```
input: "abcdefd" output: 4
```
[stackblitz](https://stackblitz.com/edit/kimura-task3?file=users%2Fkimurayoshimi%2F3.js)  1f0d828
```
node ./users/kimurayoshimi/3.js
```
> [feat]create task3

- users/itousae/1.js
**input:**
```
"abc"
```
**output:**
```
```
```
node ./users/itousae/1.js
```
> feature:lesson1

- users/kosugiyuki/2.js
input:
`["a", "b", "c"]`
output:
`"abc"`
[25079cb](https://github.com/kenmori/node-morikenjuku/commit/25079cbf4bcd03f072618357e289c9f896a5856f)
`node ./users/kosugiyuki/2.js`
> feat: work2

- users/kosugiyuki/3.js
Find e, and then return index of e as number
input:
`"abcdefd"`
output: 
`4`
[3b83047](https://github.com/kenmori/node-morikenjuku/commit/3b83047b2dd9f3f77940ba1e6dfa0253dcbbfe6f)
`node ./users/kosugiyuki/3.js`
> feat: work3

- users/kimurayoshimi/10_2.js
input
```
[
{ id: "a", value: 1 },
{ id: "b", value: 2 },
{ id: "c", value: 3 }
]
```
output
```
{
ids: ["a", "b", "c"],
entities: {
a: { value: 1 },
b: { value: 2 },
c: { value: 3 }
}
}
```
5ceefa8
```
node ./users/kimurayoshimi/10.js
```
> task10 Code for reduce only

- users/itousae/6.js
**input:**
```
```
**output:**
```
{ a: 0, b: 1, c: 2 }
```
```
node ./users/itousae/6.js
```
> feat: lesson6

- users/kosugiyuki/4.js
Filter odd number
input
`[1, 2, 3, 4, 5, 6, 7]`
output
`[1, 3, 5, 7]`
[0ab150c](https://github.com/kenmori/node-morikenjuku/commit/0ab150c0c9ee0c264c8a6db74ca77f3e08ea1324)
`node ./users/kosugiyuki/4.js`
> feat: work4

- users/itousae/7.js
**input:**
```
```
**output:**
```
{sum: "abc", length: 3}
```
```
node ./users/itousae/7.js
```
> feat: lesson7

- users/kosugiyuki/5.js
map
input
`["a", "b", "c"]`
output
`{0: "a", 1, "b", 2: "c"}`
[46ed929](https://github.com/kenmori/node-morikenjuku/commit/46ed929a3afcf3faf4726c50e82f8ac3f5c8cf98)
`node ./users/kosugiyuki/5.js`
> feat: work5

- users/itousae/8.js
**input:**
```
```
**output:**
```
[{0: "a"}, {1: "b"}, {2: "c"}]
```
```
node ./users/itousae/8.js
```
> feat: lesson8

- users/kimurayoshimi/12.js
- users/kimurayoshimi/9.js
input
```
```
output
```
false
```
input
```
[
['0', 'a'],
['1', 'b'],
['2', 'c']
]
```
output
```
{ 0: "a", 1: "b", 2: "c" }
```
> Changes and modifications to the methods used

- users/kosugiyuki/6.js
input:   ["a", "b", "c"]
output: { a: 0, b: 1, c: 2 }
Last commit: [52193be](https://github.com/kenmori/node-morikenjuku/commit/52193bea05b2894faa9934b80e8808fbc150edf2)
`node ./users/kosugiyuki/6.js`
> feat: work6

- users/kimurayoshimi/19.js
input
[1, 1, [2, 2], [[3, [4], 3], 2]]
output
[1, 1, 2, 2, 3, 4, 3, 2]
Last commit: 8abe5cc
`node ./users/kimurayoshimi/19.js`
> create task 19

- users/takedaharuna/1.js
input:  "abc"
output: ["a", "b", "c"]
Last commit: 882fb9d
`node ./users/takedaharuna/1.js`
> Feature: task01

- users/kayanooyama/1.js
input:  "abc"
output: ["a", "b", "c"]
Last commit: [91d9866](https://github.com/suefrontend/node-morikenjuku/commit/91d9866a4ad676cc2e01b15bb1815962245dfd6f)
`node ./users/kayanooyama/1.js`
> Exercise #1: String to Array Conversion

- users/kosugiyuki/7.js
output: {sum: "abc", length: 3}
Last commit: [db26810](https://github.com/kenmori/node-morikenjuku/commit/db26810500a11bd283cee8107d609f40eb08c08f)
`node ./users/kosugiyuki/7.js`
> feat: work7

- users/kayanooyama/2.js
input:  ["a", "b", "c"]
output: "abc"
Last commit: [78c58ff](https://github.com/kenmori/node-morikenjuku/pull/65/commits/78c58ff3afa3834d29827796862d262b2cce3902)
`node ./users/kayanooyama/2.js`
> Exercise #2: Array to String Conversion

- users/kayanooyama/3.js
input:  "abcdefd"
output: 4
Last commit: [75671ca](https://github.com/kenmori/node-morikenjuku/commit/75671ca0443c83ec442a244bfb3e3cf05a06a997)
`node ./users/kayanooyama/3.js`
> Exercise #3: Find Index of Character in String

- users/takedaharuna/2.js
output: "abc"
Last commit: 9549938
`node ./users/takedaharuna/2.js`
> Feature: task02

- users/kayanooyama/4.js
input:  [1, 2, 3, 4, 5, 6, 7]
output: [1, 3, 5, 7]
Last commit: [ad0e03f](https://github.com/kenmori/node-morikenjuku/commit/ad0e03f9117a26a12812349fae652904558119da)
`node ./users/kayanooyama/4.js`
> Exercise #4: Find Odd Numbers in an Array

- users/kayanooyama/5.js
input:  ["a", "b", "c"]
output: {0: "a", 1, "b", 2: "c"}
Last commit: [3d2427f](https://github.com/kenmori/node-morikenjuku/commit/3d2427fc7f54d08132f077adf9a9a04bcdc8fd19)
`node ./users/kayanooyama/5.js`
> Exercise #5: Create an Object from an Array (set element as value)

- users/kosugiyuki/8.js
output: [{0: "a"}, {1: "b"}, {2: "c"}]
Last commit: [30cf193](https://github.com/kenmori/node-morikenjuku/commit/30cf1935dbf8972213d909cf27dc535d2e0720c0)
`node ./users/kosugiyuki/8.js`
> feat: work8

- users/kayanooyama/6.js
input:  ["a", "b", "c"]
output: { a: 0, b: 1, c: 2 }
Last commit: [0210d24](https://github.com/kenmori/node-morikenjuku/commit/0210d2498e68553caf6185d0326b7fe0c6612367)
`node ./users/kayanooyama/6.js`
> Exercise #6: Create an Object from an Array (set element as key)

- users/kosugiyuki/9.js
output: false
(Search "e" element, if not exist, return false)
Last commit: [262661c](https://github.com/kenmori/node-morikenjuku/commit/262661cebab2ebe1ad0a808b5eab5bf5548bb896)
`node ./users/kosugiyuki/9.js`
> feat: work9

- users/kosugiyuki/10.js
input: 
```
[
{ id: "a", value: 1 },
{ id: "b", value: 2 },
{ id: "c", value: 3 }
]
```
output: 
```
{
ids: ["a", "b", "c"],
entities: {
a: { value: 1 },
b: { value: 2 },
c: { value: 3 }
}
}
```
Last commit: [13c0d26](https://github.com/kenmori/node-morikenjuku/commit/13c0d26ae0e49fe270d972a7d340af0fd2ea45e1)
node ./users/kosugiyuki/10.js
> feat: work10

- users/kosugiyuki/11.js
Lesson11
input: `[1, 2, 3, 4]`
output: 
```
{
sum: 10,
ids: [
{
1: { value: 1 },
2: { value: 2 },
3: { value: 3 },
4: { value: 4 }
}
]
}
```
[Stackblitz](https://stackblitz.com/edit/node-morikenjuku-hwt4lo?file=users%2Fkosugiyuki%2F11.js)
Last commit: [aea13ce](https://github.com/kenmori/node-morikenjuku/pull/78/commits/aea13cedfd21d9662202136da89dd4dfe73a28a1)
`node ./users/kosugiyuki/11.js`
> feat: work11

- users/kosugiyuki/12.js
input: 
```
[
['0', 'a'],
['1', 'b'],
['2', 'c']
]
```
output:
`{ 0: "a", 1: "b", 2: "c" }`
Last commit: [7cdfaba](https://github.com/kenmori/node-morikenjuku/commit/7cdfabab31f3a4307b42646c4d8875c616b715f4)
`node ./users/kosugiyuki/12.js`
> feat: work12

- users/kosugiyuki/13.js
input
` { a: 1, b: 2, c: 3 }`
output
` { a: 2, b: 4, c: 6 }`
Last commit: [22e309a](https://github.com/kenmori/node-morikenjuku/commit/22e309a3ba2edb9a71d50ed44e7d4b81c5abc666)
`node ./users/kosugiyuki/13.js`
> feat: work13

- users/kosugiyuki/14.js
input
`'type=listing&page=2&rowCount=10'`
output
`{type: "listing", page: "2", rowCount: "10"}`
Last commit: [708a64e](https://github.com/kenmori/node-morikenjuku/commit/708a64e577bbcb0ef21278d1b8071c33d3197992)
`node ./users/kosugiyuki/14.js`
> feat: work14

- users/takedaharuna/3.js
input: "abcdefd"
output: "4"
Last commit: 69d2c62
`node ./users/takedaharuna/3.js`
> Feature: task03

- users/kosugiyuki/15.js
input
`3`
output
```
3
2
1
0
```
Last commit: [f6f9901](https://github.com/kenmori/node-morikenjuku/commit/f6f9901703860d9c6bf0c9b06028aa32ea6f7e7e)
`node ./users/kosugiyuki/15.js`
> feat: work15

- users/chihirosakyo/5.js
input : ["a", "b", "c"]
output : {0: "a", 1, "b", 2: "c"}
Last commit: https://github.com/kenmori/node-morikenjuku/commit/565dbfb547e9ec90681ff75e04ed5e185361b589
`node ./users/chihirosakyo/5.js`
> feat: Task05

- users/takedaharuna/4.js
input: [1, 2, 3, 4, 5, 6, 7] output: [1, 3, 5, 7]
Last commit: 2a662a8
node ./users/takedaharuna/4.js
> Feature: Task04

- users/takedaharuna/5.js
output: {0: "a", 1: "b", 2: "c"}
Last commit: [004cd6d](https://github.com/kenmori/node-morikenjuku/pull/104/commits/004cd6d05d2f9736883f84dd73bb8da1c6fb16e0)
node ./users/takedaharuna/5.js
> Feature: Task05

- users/chihirosakyo/6.js
input : ["a", "b", "c"]
output : { a: 0, b: 1, c: 2 }
Last commit: https://github.com/kenmori/node-morikenjuku/commit/14985fdd0ca8ddea5695b0df0be4b3f22c74c386
`node ./users/chihirosakyo/6.js`
> feat: Task06

- users/takedaharuna/5.js
- users/takedaharuna/6.js
output: { a: 0, b: 1, c: 2 }
Last commit: [b0b8c76](https://github.com/kenmori/node-morikenjuku/pull/108/commits/b0b8c765878381e8d09332d050eb02294bfd0aca)
node ./users/takedaharuna/6.js
> Feature: task06

- users/chihirosakyo/7.js
input : ["a", "b", "c"]
output : {sum: "abc", length: 3}
Last commit: https://github.com/kenmori/node-morikenjuku/pull/109/commits/8c15c32d22cff53eeef93c8ee9afe1c1e9a8233b
`node ./users/chihirosakyo/7.js`
> feat: task07

- users/chihirosakyo/8.js
input : ["a", "b", "c"]
output : [{0: "a"}, {1: "b"}, {2: "c"}]
Last commit: https://github.com/kenmori/node-morikenjuku/commit/588b487f54ec6dd81ce9c1aa6713e81ce10fbfd6
`node ./users/chihirosakyo/8.js`
> feat: task08

- users/takedaharuna/7.js
output: {sum: "abc", length: 3}
Last commit: [e35646f](https://github.com/kenmori/node-morikenjuku/pull/111/commits/e35646ff62804259a5c308574be18a2edb7bc805)
node ./users/takedaharuna/7.js
> Feature: Task07

- users/kimurayoshimi/23.js
```
input [2, 1], [2, 3]
output [2]
```
```
input [5, 1], [2, 6]
output []
```
```
input [2, 1, 6], [2, 3, 6]
output [2, 6]
```
Last commit: 4afb5d715aad42d67d800df524bc42cb0ece31b2
`node ./users/kimurayoshimi/23.js`
> feat: task23

- users/takedaharuna/11.js
input: 
```
[1, 2, 3, 4]
```
output: 
```
{
sum: 10,
ids: [
{
1: { value: 1 },
2: { value: 2 },
3: { value: 3 },
4: { value: 4 }
}
]
}
```
- [Stackblitz](https://stackblitz.com/edit/node-k4c2eb?file=users/takedaharuna/11.js)
- Last commit: [67f3ea7](https://github.com/kenmori/node-morikenjuku/pull/121/commits/67f3ea7128751445795f9618de140a34b733765a)
- node ./users/takedaharuna/11.js
In the browser console log, I was able to output the intended value.
However, in the terminal, the output is not working...
- in browser
- in terminal
> Feature: Task11

- users/chihirosakyo/10.js
input : 
[
{ id: "a", value: 1 },
{ id: "b", value: 2 },
{ id: "c", value: 3 }
]
output : 
{
ids: ["a", "b", "c"],
entities: {
a: { value: 1 },
b: { value: 2 },
c: { value: 3 }
}
}
Last commit: https://github.com/kenmori/node-morikenjuku/commit/37b0926478771d149e30811f81fb17979080f96b
`node ./users/chihirosakyo/10.js`
> feat: task10

- users/chihirosakyo/11.js
input :  [1, 2, 3, 4]
output : 
{
sum: 10,
ids: [{ 1: { value: 1 }, 2: { value: 2 }, 3: { value: 3 }, 4: { value: 4 }}]
}
Last commit: https://github.com/kenmori/node-morikenjuku/commit/a957c1145f13d6ae4f016880334d11419275ce21
`node ./users/chihirosakyo/11.js`
When I check it in the browser it seems to work, but on Stackblitz I did not get the results I wanted.Is this a problem?
●Stackblitz
●Browser
> feat: task11

- users/natsukoseki/8.js
input : ["a", "b", "c"]  
output:[{0: "a"}, {1: "b"}, {2: "c"}]
 ](https://stackblitz.com/edit/github-femrwt?file=README.md,users%2Fnatsukoseki%2F8.js)
retest commit [1c0b6d7](https://github.com/kenmori/node-morikenjuku/commit/1c0b6d7f789df7f2bba49027c61bdbab6d3b5c82)
`node ./users/natsukoseki/8.js`
> Feature:Lesson8

- users/itousae/28.js
Remove "not", "so" element. not use Iterator method(map, forEach,...etc) and Iterator(for, while)
input: ['today', 'was', 'not', 'so', 'great']
output: [['today', 'was', 'great'], ['not', 'so']]
Last commit: 0c7906b
`node ./users/itousae/28.js`
> feat: task28

- users/itousae/29.js
input: ['a', 'b', 'c', 'a', 'c', 'd']
output: ["a", "b", "c", "d"]
Last commit: cd5a36f
`node ./users/itousae/29.js`
> feat: task29

- users/itousae/30.js
ランダムな数字があります。昇順のユニークな要素配列とそのユニーク要素が何回出現したかを表す配列を出力してください。for文で実装すること
input: [2, 2, 5, 2, 2, 2, 4, 5, 5, 9];
output: [[2,4,5,9], [5,1,3,1]]
Last commit: 2b0b491
`node ./users/itousae/30.js`
> feat: task30

- users/takedaharuna/12.js
- input: 
```
[
['0', 'a'],
['1', 'b'],
['2', 'c']
]
```
- output:
```
{ 0: "a", 1: "b", 2: "c" }
```
Last commit: [8b40725](https://github.com/kenmori/node-morikenjuku/pull/130/commits/8b40725d274c777f14a65ed3cf3bc6c89f38f563)
node ./users/takedaharuna/12.js
> Feature: task12

- users/chihirosakyo/12.js
input : 
[
['0', 'a'],
['1', 'b'],
['2', 'c']
]
output : 
{ 0: "a", 1: "b", 2: "c" }
Last commit: https://github.com/kenmori/node-morikenjuku/commit/937f450fe4a3dd7b9e8042beede76cf4da5a97ae
`node ./users/chihirosakyo/12.js`
> Feat: task12

- users/kimurayoshimi/25.js
中間と一番最初を抜き取る
Last commit: 905c1e33b107990241b0968da0646ae759487729
`node ./users/kimurayoshimi/25.js`
```
input
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
output
[5, 2, 1];
input
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
output
[6, 3, 1];
input
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
output
[8, 4, 2, 1];
```
> Feature task25

- users/takedaharuna/13.js
input: { a: 1, b: 2, c: 3 }
output: { a: 2, b: 4, c: 6 }
Last commit: [14f12ea](https://github.com/kenmori/node-morikenjuku/pull/133/commits/14f12ea029fff7a935c8dd82f4602d47c7a1bab9)
node ./users/takedaharuna/13.js
> Feature: Task13

- users/mainakagawa/3.js
input:"abcdefd" output: 4
Last commit: https://github.com/kenmori/node-morikenjuku/pull/134/commits/65158f9133ca7b23fa430baccc8296de09014bf2
`node ./users/yukamuramatsu/3.js`
> feat: lesson03

- users/chihirosakyo/13.js
input : { a: 1, b: 2, c: 3 }
output : { a: 2, b: 4, c: 6 }
Last commit: https://github.com/kenmori/node-morikenjuku/commit/7bd457b2a31cf0f310959bfe4cff625627139c11
`node ./users/chihirosakyo/13.js`
> feat: task13

- users/mainakagawa/4.js
input:[1, 2, 3, 4, 5, 6, 7] output:[1, 3, 5, 7]
Last commit: https://github.com/kenmori/node-morikenjuku/pull/136/commits/c96031118a947027e48ed10f379c93f1b886eed5
`node ./users/mainakagawa/4.js`
> feat: Filter odd number.

- users/chihirosakyo/14.js
input : 'type=listing&page=2&rowCount=10'
output : {type: "listing", page: "2", rowCount: "10"}
Last commit: https://github.com/kenmori/node-morikenjuku/commit/cdec281dbafc52a5b6edd027983ceb054efc4e1f
`node ./users/chihirosakyo/14.js`
> feat:task14

- users/mainakagawa/5.js
input ["a", "b", "c"]
output{0: "a", 1, "b", 2: "c"}
Last commit: https://github.com/kenmori/node-morikenjuku/commit/400eeadafb93a2da69643f09e8af162f51490fa8
`node ./users/mainakagwa/5.js`
> feat: Convert array to object.

- users/takedaharuna/15.js
input: 3
output: 
3
2
1
0
Last commit: [dd0b604](https://github.com/kenmori/node-morikenjuku/pull/140/commits/dd0b60447b729906a84f9f885f2b6c1b43210b92)
node ./users/takedaharuna/15.js
> Feature: task15

- users/takedaharuna/16.js
input: "abcdefg"
output: "gfedcba"
Last commit: [3aab08a](https://github.com/kenmori/node-morikenjuku/pull/141/commits/3aab08afd6c09e266716be128f7cb75bd4e51970)
node ./users/takedaharuna/16.js
> Feature: task16

- users/takedaharuna/17.js
- input
`{ 1: "a", 2: "b", 3: "c" }`
- output
```
[
['1', 'a'],
['2', 'b'],
['3', 'c']
]
```
Last commit: [0a30691](https://github.com/kenmori/node-morikenjuku/pull/142/commits/0a30691e83ae96fd2ef22da33698aafbeb657773)
node ./users/takedaharuna/17.js
> Feature: task17

- users/takedaharuna/19.js
input: [1, 1, [2, 2], [[3, [4], 3], 2]]
output: [1, 1, 2, 2, 3, 4, 3, 2]
Last commit: [49a5996](https://github.com/kenmori/node-morikenjuku/pull/144/commits/49a5996cdfa17d44d459cff7c79a92eb711ba963)
node ./users/takedaharuna/19.js
> Feature: task19
